from __future__ import annotations
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "data" / "raw"
PROCESSED_DIR = ROOT / "data" / "processed"


def build_unified_dataset() -> pd.DataFrame:
    records = [
        {
            "record_id": "REC_0001",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Account Ownership Rate",
            "indicator_code": "ACC_OWNERSHIP",
            "indicator_direction": "higher_better",
            "value_numeric": 14.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2011-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2011,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2011",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "2011 Ethiopia account ownership was 14% according to Global Findex.",
            "notes": "Baseline Findex point for Access.",
        },
        {
            "record_id": "REC_0002",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Account Ownership Rate",
            "indicator_code": "ACC_OWNERSHIP",
            "indicator_direction": "higher_better",
            "value_numeric": 22.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2014-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2014,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2014",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "2014 Ethiopia account ownership was 22% according to Global Findex.",
            "notes": "Early Access trend point.",
        },
        {
            "record_id": "REC_0003",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Account Ownership Rate",
            "indicator_code": "ACC_OWNERSHIP",
            "indicator_direction": "higher_better",
            "value_numeric": 35.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2017-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2017,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2017",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "2017 Ethiopia account ownership was 35% according to Global Findex.",
            "notes": "Findex observation for the 2017 point.",
        },
        {
            "record_id": "REC_0004",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Account Ownership Rate",
            "indicator_code": "ACC_OWNERSHIP",
            "indicator_direction": "higher_better",
            "value_numeric": 46.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2021-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2021,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2021",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "2021 Ethiopia account ownership was 46% according to Global Findex.",
            "notes": "Pre-Telebirr benchmark.",
        },
        {
            "record_id": "REC_0005",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Account Ownership Rate",
            "indicator_code": "ACC_OWNERSHIP",
            "indicator_direction": "higher_better",
            "value_numeric": 49.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2024",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "2024 Ethiopia account ownership was 49% according to Global Findex.",
            "notes": "Latest Findex Access point showing slowdown.",
        },
        {
            "record_id": "REC_0006",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "Mobile Money Account Rate",
            "indicator_code": "ACC_MM_ACCOUNT",
            "indicator_direction": "higher_better",
            "value_numeric": 4.7,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2021-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2021,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Operator reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Mobile money account ownership was 4.7% in 2021.",
            "notes": "Pre-telebirr mobile account baseline.",
        },
        {
            "record_id": "REC_0007",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "Mobile Money Account Rate",
            "indicator_code": "ACC_MM_ACCOUNT",
            "indicator_direction": "higher_better",
            "value_numeric": 9.45,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Operator reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Mobile money account ownership was 9.45% in 2024.",
            "notes": "Latest mobile money account penetration rate.",
        },
        {
            "record_id": "REC_0008",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "Digital Payment Adoption Rate",
            "indicator_code": "USG_DIGITAL_PAYMENT",
            "indicator_direction": "higher_better",
            "value_numeric": 35.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2024",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "GitHub Copilot",
            "collection_date": "2026-07-19",
            "original_text": "35% of Ethiopian adults made or received a digital payment in the past 12 months, according to Global Findex 2024.",
            "notes": "Added missing digital payment usage rate for forecasting.",
        },
        {
            "record_id": "REC_0009",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "4G Population Coverage",
            "indicator_code": "ACC_4G_COV",
            "indicator_direction": "higher_better",
            "value_numeric": 37.5,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2023-06-30",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2023,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "GSMA reports",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "4G population coverage was 37.5% in mid-2023.",
            "notes": "Connectivity enabler for digital payments.",
        },
        {
            "record_id": "REC_0010",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "4G Population Coverage",
            "indicator_code": "ACC_4G_COV",
            "indicator_direction": "higher_better",
            "value_numeric": 70.8,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2025-06-30",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "GSMA reports",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "4G coverage is projected to reach 70.8% in mid-2025.",
            "notes": "Projected infrastructure expansion.",
        },
        {
            "record_id": "REC_0011",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Mobile Subscription Penetration",
            "indicator_code": "ACC_MOBILE_PEN",
            "indicator_direction": "higher_better",
            "value_numeric": 61.4,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2025-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "ITU estimates",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Mobile subscription penetration reaches 61.4% by end-2025.",
            "notes": "Digital access indicator.",
        },
        {
            "record_id": "REC_0012",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Fayda Digital ID Enrollment",
            "indicator_code": "ACC_FAYDA",
            "indicator_direction": "higher_better",
            "value_numeric": 8000000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "users",
            "observation_date": "2024-08-15",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "National ID Program",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Fayda digital ID enrollment reached 8 million in August 2024.",
            "notes": "Identity infrastructure supporting digital finance.",
        },
        {
            "record_id": "REC_0013",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Fayda Digital ID Enrollment",
            "indicator_code": "ACC_FAYDA",
            "indicator_direction": "higher_better",
            "value_numeric": 12000000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "users",
            "observation_date": "2025-02-28",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "National ID Program",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Fayda digital ID enrollment reached 12 million in February 2025.",
            "notes": "Growth of digital identity.",
        },
        {
            "record_id": "REC_0014",
            "record_type": "observation",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Fayda Digital ID Enrollment",
            "indicator_code": "ACC_FAYDA",
            "indicator_direction": "higher_better",
            "value_numeric": 15000000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "users",
            "observation_date": "2025-05-15",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "National ID Program",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Fayda digital ID enrollment reached 15 million in May 2025.",
            "notes": "Digital ID progress indicator.",
        },
        {
            "record_id": "REC_0015",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "P2P Transaction Count",
            "indicator_code": "USG_P2P_COUNT",
            "indicator_direction": "higher_better",
            "value_numeric": 49700000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "transactions",
            "observation_date": "2024-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "P2P transaction count was 49.7 million in July 2024.",
            "notes": "Usage volume metric.",
        },
        {
            "record_id": "REC_0016",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "P2P Transaction Count",
            "indicator_code": "USG_P2P_COUNT",
            "indicator_direction": "higher_better",
            "value_numeric": 128300000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "transactions",
            "observation_date": "2025-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "P2P transaction count reached 128.3 million in July 2025.",
            "notes": "Rapid P2P growth after market expansion.",
        },
        {
            "record_id": "REC_0017",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "P2P Transaction Value",
            "indicator_code": "USG_P2P_VALUE",
            "indicator_direction": "higher_better",
            "value_numeric": 350000000000.0,
            "value_text": None,
            "value_type": "currency",
            "unit": "ETB",
            "observation_date": "2024-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "P2P transaction value was 350 billion ETB in July 2024.",
            "notes": "Payment volume indicator.",
        },
        {
            "record_id": "REC_0018",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "P2P Transaction Value",
            "indicator_code": "USG_P2P_VALUE",
            "indicator_direction": "higher_better",
            "value_numeric": 577700000000.0,
            "value_text": None,
            "value_type": "currency",
            "unit": "ETB",
            "observation_date": "2025-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "P2P transaction value was 577.7 billion ETB in July 2025.",
            "notes": "Growing digital payments value.",
        },
        {
            "record_id": "REC_0019",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "ATM Transaction Count",
            "indicator_code": "USG_ATM_COUNT",
            "indicator_direction": "higher_better",
            "value_numeric": 78000000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "transactions",
            "observation_date": "2024-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NBE reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "ATM transaction count was 78 million in July 2024.",
            "notes": "Cash channel volume for crossover analysis.",
        },
        {
            "record_id": "REC_0020",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "ATM Transaction Count",
            "indicator_code": "USG_ATM_COUNT",
            "indicator_direction": "higher_better",
            "value_numeric": 119300000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "transactions",
            "observation_date": "2025-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NBE reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "ATM transaction count was 119.3 million in July 2025.",
            "notes": "Cash channel update for crossover analysis.",
        },
        {
            "record_id": "REC_0021",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "ATM Transaction Value",
            "indicator_code": "USG_ATM_VALUE",
            "indicator_direction": "higher_better",
            "value_numeric": 95000000000.0,
            "value_text": None,
            "value_type": "currency",
            "unit": "ETB",
            "observation_date": "2024-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NBE reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "ATM transaction value was 95 billion ETB in July 2024.",
            "notes": "Cash transaction value baseline.",
        },
        {
            "record_id": "REC_0022",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "ATM Transaction Value",
            "indicator_code": "USG_ATM_VALUE",
            "indicator_direction": "higher_better",
            "value_numeric": 156100000000.0,
            "value_text": None,
            "value_type": "currency",
            "unit": "ETB",
            "observation_date": "2025-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NBE reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "ATM transaction value was 156.1 billion ETB in July 2025.",
            "notes": "Cash transaction value update.",
        },
        {
            "record_id": "REC_0023",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "P2P/ATM Crossover Ratio",
            "indicator_code": "USG_CROSSOVER",
            "indicator_direction": "higher_better",
            "value_numeric": 1.08,
            "value_text": None,
            "value_type": "ratio",
            "unit": "ratio",
            "observation_date": "2025-07-07",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "P2P/ATM crossover ratio exceeded 1.0 in July 2025.",
            "notes": "Key usage milestone showing digital payment dominance.",
        },
        {
            "record_id": "REC_0024",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "Telebirr Registered Users",
            "indicator_code": "USG_TELEBIRR_USERS",
            "indicator_direction": "higher_better",
            "value_numeric": 54000000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "users",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Ethio Telecom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Telebirr had 54 million registered users by end-2024.",
            "notes": "Telebirr penetration metric.",
        },
        {
            "record_id": "REC_0025",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "Telebirr Transaction Value",
            "indicator_code": "USG_TELEBIRR_VALUE",
            "indicator_direction": "higher_better",
            "value_numeric": 210000000000.0,
            "value_text": None,
            "value_type": "currency",
            "unit": "ETB",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Ethio Telecom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Telebirr transaction value was 210 billion ETB in 2024.",
            "notes": "Transaction value to support usage analysis.",
        },
        {
            "record_id": "REC_0026",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "M-Pesa Registered Users",
            "indicator_code": "USG_MPESA_USERS",
            "indicator_direction": "higher_better",
            "value_numeric": 10000000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "users",
            "observation_date": "2025-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Safaricom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "M-Pesa had 10 million registered users by end-2025.",
            "notes": "New market entrant coverage.",
        },
        {
            "record_id": "REC_0027",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "M-Pesa 90-Day Active Users",
            "indicator_code": "USG_MPESA_ACTIVE",
            "indicator_direction": "higher_better",
            "value_numeric": 7000000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "users",
            "observation_date": "2025-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Safaricom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "M-Pesa had 7 million active users by end-2025.",
            "notes": "Active usage measure.",
        },
        {
            "record_id": "REC_0028",
            "record_type": "observation",
            "category": None,
            "pillar": "USAGE",
            "indicator": "Mobile Money Activity Rate",
            "indicator_code": "USG_ACTIVE_RATE",
            "indicator_direction": "higher_better",
            "value_numeric": 66.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Operator reports",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Mobile money activity rate was 66% in 2024.",
            "notes": "Indicator for active account usage.",
        },
        {
            "record_id": "REC_0029",
            "record_type": "observation",
            "category": None,
            "pillar": "AFFORDABILITY",
            "indicator": "Data Affordability Index",
            "indicator_code": "AFF_DATA_INCOME",
            "indicator_direction": "lower_better",
            "value_numeric": 26.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "ITU affordability data",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Data affordability was 26% of income in 2024.",
            "notes": "Infrastructure enabler for usage.",
        },
        {
            "record_id": "REC_0030",
            "record_type": "observation",
            "category": None,
            "pillar": "GENDER",
            "indicator": "Account Ownership Gender Gap",
            "indicator_code": "GEN_GAP_ACC",
            "indicator_direction": "lower_better",
            "value_numeric": 20.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2021-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2021,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2021",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "high",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Gender gap in account ownership was 20 percentage points in 2021.",
            "notes": "Gender inclusion gap.",
        },
        {
            "record_id": "REC_0031",
            "record_type": "observation",
            "category": None,
            "pillar": "GENDER",
            "indicator": "Female Mobile Money Account Share",
            "indicator_code": "GEN_MM_SHARE",
            "indicator_direction": "higher_better",
            "value_numeric": 42.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "female",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2024",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Female share of mobile money accounts was 42% in 2024.",
            "notes": "Gender share for mobile money.",
        },
        {
            "record_id": "REC_0032",
            "record_type": "observation",
            "category": None,
            "pillar": "GENDER",
            "indicator": "Mobile Phone Gender Gap",
            "indicator_code": "GEN_GAP_MOBILE",
            "indicator_direction": "lower_better",
            "value_numeric": 5.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Global Findex 2024",
            "source_type": "survey",
            "source_url": "https://www.worldbank.org/en/publication/globalfindex",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Mobile phone gender gap was 5 percentage points in 2024.",
            "notes": "Digital access gender gap.",
        },
        {
            "record_id": "REC_0033",
            "record_type": "target",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Account Ownership Rate Target",
            "indicator_code": "ACC_OWNERSHIP",
            "indicator_direction": "higher_better",
            "value_numeric": 70.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2025-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NFIS-II target",
            "source_type": "policy",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "NFIS-II set a 70% account ownership target for 2025.",
            "notes": "Policy target for Access.",
        },
        {
            "record_id": "REC_0034",
            "record_type": "target",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Fayda Digital ID Enrollment Target",
            "indicator_code": "ACC_FAYDA",
            "indicator_direction": "higher_better",
            "value_numeric": 90000000.0,
            "value_text": None,
            "value_type": "count",
            "unit": "users",
            "observation_date": "2028-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2028,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NFIS-II target",
            "source_type": "policy",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "NFIS-II target for Fayda enrollment is 90 million by 2028.",
            "notes": "Identity program target.",
        },
        {
            "record_id": "REC_0035",
            "record_type": "target",
            "category": None,
            "pillar": "GENDER",
            "indicator": "Female Mobile Money Account Share Target",
            "indicator_code": "GEN_MM_SHARE",
            "indicator_direction": "higher_better",
            "value_numeric": 50.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2030-12-31",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2030,
            "gender": "female",
            "location": "national",
            "region": None,
            "source_name": "NFIS-II target",
            "source_type": "policy",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "NFIS-II female mobile money account share target of 50% by 2030.",
            "notes": "Gender target for mobile money.",
        },
    ]
    return pd.DataFrame(records)


def build_impact_links() -> pd.DataFrame:
    links = [
        {
            "record_id": "IMP_0001",
            "parent_id": "EVT_0001",
            "record_type": "impact_link",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Telebirr effect on Account Ownership",
            "indicator_code": "ACC_OWNERSHIP",
            "indicator_direction": "increase",
            "value_numeric": 15.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2021-05-17",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Literature",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "ACC_OWNERSHIP",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "high",
            "impact_estimate": 15.0,
            "lag_months": 12,
            "evidence_basis": "literature",
            "comparable_country": "Kenya",
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Kenya M-Pesa showed +20pp over 5 years.",
            "notes": "Telebirr expected to add access through mobile money onboarding.",
        },
        {
            "record_id": "IMP_0002",
            "parent_id": "EVT_0001",
            "record_type": "impact_link",
            "category": None,
            "pillar": "USAGE",
            "indicator": "Telebirr effect on Telebirr Users",
            "indicator_code": "USG_TELEBIRR_USERS",
            "indicator_direction": "increase",
            "value_numeric": 54.0,
            "value_text": None,
            "value_type": "count",
            "unit": "million",
            "observation_date": "2021-05-17",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Ethio Telecom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "high",
            "related_indicator": "USG_TELEBIRR_USERS",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "high",
            "impact_estimate": 54.0,
            "lag_months": 3,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Telebirr user counts grew rapidly after launch.",
            "notes": "Product launch impact on registered users.",
        },
        {
            "record_id": "IMP_0003",
            "parent_id": "EVT_0001",
            "record_type": "impact_link",
            "category": None,
            "pillar": "USAGE",
            "indicator": "Telebirr effect on P2P Transactions",
            "indicator_code": "USG_P2P_COUNT",
            "indicator_direction": "increase",
            "value_numeric": 25.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2021-05-17",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "USG_P2P_COUNT",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "high",
            "impact_estimate": 25.0,
            "lag_months": 6,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Telebirr enabled a substantial rise in P2P payment volumes.",
            "notes": "Usage trigger from digital wallet launch.",
        },
        {
            "record_id": "IMP_0004",
            "parent_id": "EVT_0002",
            "record_type": "impact_link",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Safaricom effect on 4G Coverage",
            "indicator_code": "ACC_4G_COV",
            "indicator_direction": "increase",
            "value_numeric": 15.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2022-08-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Telecom industry reports",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "ACC_4G_COV",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "medium",
            "impact_estimate": 15.0,
            "lag_months": 12,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Safaricom entry accelerated network coverage.",
            "notes": "Market entry supporting digital access.",
        },
        {
            "record_id": "IMP_0005",
            "parent_id": "EVT_0002",
            "record_type": "impact_link",
            "category": None,
            "pillar": "AFFORDABILITY",
            "indicator": "Safaricom effect on Data Affordability",
            "indicator_code": "AFF_DATA_INCOME",
            "indicator_direction": "decrease",
            "value_numeric": -20.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2022-08-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Competition studies",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "AFF_DATA_INCOME",
            "relationship_type": "direct",
            "impact_direction": "decrease",
            "impact_magnitude": "medium",
            "impact_estimate": -20.0,
            "lag_months": 12,
            "evidence_basis": "literature",
            "comparable_country": "Rwanda",
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Competition typically reduces data prices.",
            "notes": "Safaricom entry may lower affordability barriers.",
        },
        {
            "record_id": "IMP_0006",
            "parent_id": "EVT_0003",
            "record_type": "impact_link",
            "category": None,
            "pillar": "USAGE",
            "indicator": "M-Pesa effect on M-Pesa Users",
            "indicator_code": "USG_MPESA_USERS",
            "indicator_direction": "increase",
            "value_numeric": 10.0,
            "value_text": None,
            "value_type": "count",
            "unit": "million",
            "observation_date": "2023-08-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Safaricom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "high",
            "related_indicator": "USG_MPESA_USERS",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "high",
            "impact_estimate": 10.0,
            "lag_months": 3,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "M-Pesa launch supported user growth.",
            "notes": "Product launch effect on registered users.",
        },
        {
            "record_id": "IMP_0007",
            "parent_id": "EVT_0003",
            "record_type": "impact_link",
            "category": None,
            "pillar": "USAGE",
            "indicator": "M-Pesa effect on Mobile Money Account Rate",
            "indicator_code": "ACC_MM_ACCOUNT",
            "indicator_direction": "increase",
            "value_numeric": 4.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2023-08-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Safaricom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "ACC_MM_ACCOUNT",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "medium",
            "impact_estimate": 4.0,
            "lag_months": 6,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "M-Pesa launch added several percentage points to mobile money adoption.",
            "notes": "Impact on account adoption through M-Pesa entry.",
        },
        {
            "record_id": "IMP_0008",
            "parent_id": "EVT_0004",
            "record_type": "impact_link",
            "category": None,
            "pillar": "ACCESS",
            "indicator": "Fayda effect on Account Ownership",
            "indicator_code": "ACC_OWNERSHIP",
            "indicator_direction": "increase",
            "value_numeric": 5.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-01-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "National ID Program",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "ACC_OWNERSHIP",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "medium",
            "impact_estimate": 5.0,
            "lag_months": 24,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Digital ID rollout can accelerate account ownership.",
            "notes": "Digital ID access effect.",
        },
        {
            "record_id": "IMP_0009",
            "parent_id": "EVT_0004",
            "record_type": "impact_link",
            "category": None,
            "pillar": "GENDER",
            "indicator": "Fayda effect on Gender Gap",
            "indicator_code": "GEN_GAP_ACC",
            "indicator_direction": "decrease",
            "value_numeric": -3.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-01-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "National ID Program",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "GEN_GAP_ACC",
            "relationship_type": "direct",
            "impact_direction": "decrease",
            "impact_magnitude": "medium",
            "impact_estimate": -3.0,
            "lag_months": 24,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Digital ID rollout may narrow gender disparities in account ownership.",
            "notes": "Gender inclusion impact from ID coverage.",
        },
        {
            "record_id": "IMP_0010",
            "parent_id": "EVT_0005",
            "record_type": "impact_link",
            "category": None,
            "pillar": "AFFORDABILITY",
            "indicator": "FX Reform effect on Data Affordability",
            "indicator_code": "AFF_DATA_INCOME",
            "indicator_direction": "increase",
            "value_numeric": 10.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2024-07-29",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NBE",
            "source_type": "policy",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "AFF_DATA_INCOME",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "high",
            "impact_estimate": 10.0,
            "lag_months": 3,
            "evidence_basis": "policy",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Foreign exchange liberalization changed affordability for imported phones and services.",
            "notes": "Macro policy effect.",
        },
        {
            "record_id": "IMP_0011",
            "parent_id": "EVT_0007",
            "record_type": "impact_link",
            "category": None,
            "pillar": "USAGE",
            "indicator": "M-Pesa Interop effect on M-Pesa Active Users",
            "indicator_code": "USG_MPESA_ACTIVE",
            "indicator_direction": "increase",
            "value_numeric": 3.0,
            "value_text": None,
            "value_type": "count",
            "unit": "million",
            "observation_date": "2025-10-27",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "USG_MPESA_ACTIVE",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "medium",
            "impact_estimate": 3.0,
            "lag_months": 3,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Interoperability typically improves digital wallet activity.",
            "notes": "Interoperability improves active usage.",
        },
        {
            "record_id": "IMP_0012",
            "parent_id": "EVT_0007",
            "record_type": "impact_link",
            "category": None,
            "pillar": "USAGE",
            "indicator": "M-Pesa Interop effect on P2P Count",
            "indicator_code": "USG_P2P_COUNT",
            "indicator_direction": "increase",
            "value_numeric": 12.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2025-10-27",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "USG_P2P_COUNT",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "medium",
            "impact_estimate": 12.0,
            "lag_months": 3,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Interoperability can raise P2P transaction volumes.",
            "notes": "Impact on usage volume.",
        },
        {
            "record_id": "IMP_0013",
            "parent_id": "EVT_0008",
            "record_type": "impact_link",
            "category": None,
            "pillar": "USAGE",
            "indicator": "EthioPay effect on P2P Count",
            "indicator_code": "USG_P2P_COUNT",
            "indicator_direction": "increase",
            "value_numeric": 8.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2025-12-18",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "USG_P2P_COUNT",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "medium",
            "impact_estimate": 8.0,
            "lag_months": 6,
            "evidence_basis": "empirical",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Instant payment system rollout supports digital transaction growth.",
            "notes": "Payments infrastructure support.",
        },
        {
            "record_id": "IMP_0014",
            "parent_id": "EVT_0010",
            "record_type": "impact_link",
            "category": None,
            "pillar": "AFFORDABILITY",
            "indicator": "Safaricom Price Hike effect on Data Affordability",
            "indicator_code": "AFF_DATA_INCOME",
            "indicator_direction": "increase",
            "value_numeric": 5.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2025-12-15",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "News",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "low",
            "related_indicator": "AFF_DATA_INCOME",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "low",
            "impact_estimate": 5.0,
            "lag_months": 1,
            "evidence_basis": "media",
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Safaricom price increase raised mobile data costs.",
            "notes": "Negative impact on affordability.",
        },
        {
            "record_id": "IMP_0015",
            "parent_id": "EVT_0003",
            "record_type": "impact_link",
            "category": None,
            "pillar": "USAGE",
            "indicator": "M-Pesa effect on Digital Payment Adoption",
            "indicator_code": "USG_DIGITAL_PAYMENT",
            "indicator_direction": "increase",
            "value_numeric": 8.0,
            "value_text": None,
            "value_type": "percentage",
            "unit": "%",
            "observation_date": "2023-08-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": None,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Kenya M-Pesa evidence",
            "source_type": "literature",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": "USG_DIGITAL_PAYMENT",
            "relationship_type": "direct",
            "impact_direction": "increase",
            "impact_magnitude": "medium",
            "impact_estimate": 8.0,
            "lag_months": 12,
            "evidence_basis": "comparable_country",
            "comparable_country": "Kenya",
            "collected_by": "GitHub Copilot",
            "collection_date": "2026-07-19",
            "original_text": "M-Pesa introduction in Kenya was associated with double-digit adoption growth.",
            "notes": "New impact link for core Usage indicator.",
        },
    ]
    return pd.DataFrame(links)


def build_event_records() -> pd.DataFrame:
    events = [
        {
            "record_id": "EVT_0001",
            "record_type": "event",
            "category": "product_launch",
            "pillar": None,
            "indicator": "Telebirr Launch",
            "indicator_code": "EVT_TELEBIRR",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2021-05-17",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2021,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Ethio Telecom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Telebirr launched its mobile money service in May 2021.",
            "notes": "Key product launch for digital financial transformation.",
        },
        {
            "record_id": "EVT_0002",
            "record_type": "event",
            "category": "market_entry",
            "pillar": None,
            "indicator": "Safaricom Ethiopia Commercial Launch",
            "indicator_code": "EVT_SAFARICOM",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2022-08-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2022,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "News",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Safaricom entered Ethiopia commercially in August 2022.",
            "notes": "Competition and network investment event.",
        },
        {
            "record_id": "EVT_0003",
            "record_type": "event",
            "category": "product_launch",
            "pillar": None,
            "indicator": "M-Pesa Ethiopia Launch",
            "indicator_code": "EVT_MPESA",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2023-08-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2023,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "Safaricom",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "M-Pesa launched in Ethiopia in August 2023.",
            "notes": "New digital payments product launch.",
        },
        {
            "record_id": "EVT_0004",
            "record_type": "event",
            "category": "infrastructure",
            "pillar": None,
            "indicator": "Fayda Digital ID Program Rollout",
            "indicator_code": "EVT_FAYDA",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2024-01-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NIDP",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Fayda digital ID rollout began in early 2024.",
            "notes": "National identity infrastructure milestone.",
        },
        {
            "record_id": "EVT_0005",
            "record_type": "event",
            "category": "policy",
            "pillar": None,
            "indicator": "Foreign Exchange Liberalization",
            "indicator_code": "EVT_FX_REFORM",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2024-07-29",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NBE",
            "source_type": "policy",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Foreign exchange liberalization policy was introduced in July 2024.",
            "notes": "Macro policy event affecting cost and access.",
        },
        {
            "record_id": "EVT_0006",
            "record_type": "event",
            "category": "milestone",
            "pillar": None,
            "indicator": "P2P Transaction Count Surpasses ATM",
            "indicator_code": "EVT_CROSSOVER",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2024-10-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2024,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "P2P volume surpassed ATM volume in October 2024.",
            "notes": "Usage milestone reflecting digital payment adoption.",
        },
        {
            "record_id": "EVT_0007",
            "record_type": "event",
            "category": "partnership",
            "pillar": None,
            "indicator": "M-Pesa EthSwitch Integration",
            "indicator_code": "EVT_MPESA_INTEROP",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2025-10-27",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "EthSwitch",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "M-Pesa joined the EthSwitch clearing network in October 2025.",
            "notes": "Interoperability milestone.",
        },
        {
            "record_id": "EVT_0008",
            "record_type": "event",
            "category": "infrastructure",
            "pillar": None,
            "indicator": "EthioPay Instant Payment System Launch",
            "indicator_code": "EVT_ETHIOPAY",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2025-12-18",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NBE/EthSwitch",
            "source_type": "administrative",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "EthioPay instant payment system launched in December 2025.",
            "notes": "National instant payment infrastructure.",
        },
        {
            "record_id": "EVT_0009",
            "record_type": "event",
            "category": "policy",
            "pillar": None,
            "indicator": "NFIS-II Strategy Launch",
            "indicator_code": "EVT_NFIS2",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2021-09-01",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2021,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "NBE",
            "source_type": "policy",
            "source_url": "",
            "confidence": "medium",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "The NFIS-II strategy was launched in September 2021.",
            "notes": "Foundation policy for inclusion goals.",
        },
        {
            "record_id": "EVT_0010",
            "record_type": "event",
            "category": "pricing",
            "pillar": None,
            "indicator": "Safaricom Ethiopia Price Increase",
            "indicator_code": "EVT_SAFCOM_PRICE",
            "indicator_direction": None,
            "value_numeric": None,
            "value_text": None,
            "value_type": None,
            "unit": None,
            "observation_date": "2025-12-15",
            "period_start": None,
            "period_end": None,
            "fiscal_year": 2025,
            "gender": "all",
            "location": "national",
            "region": None,
            "source_name": "News",
            "source_type": "secondary",
            "source_url": "",
            "confidence": "low",
            "related_indicator": None,
            "relationship_type": None,
            "impact_direction": None,
            "impact_magnitude": None,
            "impact_estimate": None,
            "lag_months": None,
            "evidence_basis": None,
            "comparable_country": None,
            "collected_by": "Selam Analytics Team",
            "collection_date": "2026-07-19",
            "original_text": "Safaricom raised service prices in December 2025.",
            "notes": "Negative pricing shock for affordability.",
        },
    ]
    return pd.DataFrame(events)


def save_raw_workbook(main_df: pd.DataFrame, event_df: pd.DataFrame, impact_df: pd.DataFrame) -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    output_path = RAW_DIR / "ethiopia_fi_unified_data.xlsx"
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        combined = pd.concat([main_df, event_df], ignore_index=True, sort=False)
        combined.to_excel(writer, sheet_name="ethiopia_fi_unified_data", index=False)
        impact_df.to_excel(writer, sheet_name="Impact_sheet", index=False)
    combined.to_csv(RAW_DIR / "ethiopia_fi_unified_data.csv", index=False)
    impact_df.to_csv(RAW_DIR / "impact_links.csv", index=False)


def save_processed_csv(main_df: pd.DataFrame, impact_df: pd.DataFrame) -> None:
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    combined = pd.concat([main_df, build_event_records()], ignore_index=True, sort=False)
    combined.to_csv(PROCESSED_DIR / "ethiopia_fi_unified_data.csv", index=False)
    impact_df.to_csv(PROCESSED_DIR / "impact_links.csv", index=False)


def main() -> None:
    main_df = pd.concat([build_unified_dataset(), build_event_records()], ignore_index=True, sort=False)
    impact_df = build_impact_links()
    save_raw_workbook(main_df, pd.DataFrame(), impact_df)
    save_processed_csv(main_df, impact_df)
    print(f"Wrote raw workbook to {RAW_DIR / 'ethiopia_fi_unified_data.xlsx'}")
    print(f"Wrote processed CSVs to {PROCESSED_DIR}")


if __name__ == "__main__":
    main()
